name: 'test'
on: # rebuild any PRs and main branch changes
  pull_request:

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: changed-files
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          separator: ','
      - name: output results
        shell: bash
        env:
          OUTPUT_ANY_CHANGED: ${{ steps.changed-files.outputs.any_changed }}
          OUTPUT_ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          OUTPUT_ANY_ADDED: ${{ steps.changed-files.outputs.any_added }}
          OUTPUT_ANY_MODIFIED: ${{ steps.changed-files.outputs.any_modified }}
          OUTPUT_ANY_DELETED: ${{ steps.changed-files.outputs.any_deleted }}
          OUTPUT_ONLY_ADDED_FILES: ${{ steps.changed-files.outputs.only_added }}
          OUTPUT_ONLY_MODIFIED_FILES: ${{ steps.changed-files.outputs.only_modified }}
          OUTPUT_ONLY_DELETED_FILES: ${{ steps.changed-files.outputs.only_deleted }}
        run: |
          echo "any_changed=${OUTPUT_ANY_CHANGED}"
          echo "all_changed_files=${OUTPUT_ALL_CHANGED_FILES}"
          echo "any_added=${OUTPUT_ANY_ADDED}"
          echo "any_modified=${OUTPUT_ANY_MODIFIED}"
          echo "any_deleted=${OUTPUT_ANY_DELETED}"
          echo "only_added=${OUTPUT_ONLY_ADDED_FILES}"
          echo "only_modified=${OUTPUT_ONLY_MODIFIED_FILES}"
          echo "only_deleted=${OUTPUT_ONLY_DELETED_FILES}"
